[tool.djlint]
linters = ["jinja"]
blank_line_after_tag = "load,extends,include"
blank_line_before_tag = "load,extends,include"
close_void_tags = true
#extension = ".html"
ignore_blocks = "raw,example"
include = "H014,H015"
indent = 5
line_break_after_multiline_tag = true

[tool.djlint.per-file-ignores]
"file.html" = "H026,H025"
"file_two.html" = "H001"